language: elixir

elixir:
  - 1.6.1
  - 1.5.0
  - 1.4.5
  - 1.4.2
otp_release:
  - 19.3
  - 20.0
  - 20.2

matrix:
  exclude:
  - elixir: 1.4.2
    otp_release: 20.0
  - elixir: 1.4.2
    otp_release: 20.2
